fs:
  root: "/quickshare/root"
  opensLimit: 128
  openTTL: 60 # 1 min
secrets:
  tokenSecret: ""
server:
  debug: false
  host: "0.0.0.0"
  port: 8686
  readTimeout: 2000
  writerTimeout: 86400000 # 1 day
  maxHeaderBytes: 512
  publicPath: "/quickshare/public"
  captchaWidth: 256
  captchaHeight: 60
  captchaEnabled: true
  uploadSpeedLimit: 102400 # 100k/limiterCyc
  downloadSpeedLimit: 102400 # 100k/limiterCyc
  spaceLimit: 1024 # 1GB
  limiterCapacity: 1000
  limiterCyc: 1000 # 1s
users:
  enableAuth: true
  defaultAdmin: ""
  defaultAdminPwd: ""
  cookieTTL: 604800 # 1 week
  cookieSecure: false
  cookieHttpOnly: true
  minUserNameLen: 4
  minPwdLen: 6
